GET http://geoili.me:3000/users


###
GET http://geoili.me:3000/users/5db6af244a0a8f701431fdf1


###

POST http://geoili.me:3000/users
Content-Type: application/json

{
	"name":"George",
	"email":"test@test.com"
}

###
GET http://geoili.me:3000/quizes


###

POST http://geoili.me:3000/quizes
Content-Type: application/json

{
	"name":"Quiz 8",
	"questions":[
		{
		"questionTitle" : "Question 1",
		"answerA": "A",
		"answerB": "B",
		"answerC": "C",
		"answerD": "D",
		"correctAnswer":1
	},
		{
		"questionTitle" : "Question 2",
		"answerA": "A",
		"answerB": "B",
		"answerC": "C",
		"answerD": "D",
		"correctAnswer":1
	},
		{
		"questionTitle" : "Question 4",
		"answerA": "A",
		"answerB": "B",
		"answerC": "C",
		"answerD": "D",
		"correctAnswer":1
	},
		{
		"questionTitle" : "Question 2",
		"answerA": "A",
		"answerB": "B",
		"answerC": "C",
		"answerD": "D",
		"correctAnswer":1
	}
	]
}

###